### ISSUE TITLE
Elixir: Experimental to Beta/GA?

### ISSUE THREAD

**Issue by Nezteb** [semgrep/semgrep-elixir#1]
Thanks to https://github.com/returntocorp/semgrep/issues/3698 and this repo, Semgrep supports Elixir.

[Elixir is currently listed as "experimental"](https://github.com/returntocorp/semgrep#language-support). Is there anything specific that needs to be done to get it up to Beta or GA status?

**Comment by mjambon** [comment]
Hi, this repo is only for generated code (sorry, issues should be disabled). I invite you to post the question to the semgrep repo or to our community Slack.
